
def exibir_menu_usuario():
    print("\n" + "="*30)
    print("\n--- Menu do Usuário ---")
    print("="*30)
    print("1. Planos de Treino")
    print("2. Atividades")
    print("3. Nutrição")
    print("4. Metas")
    print("5. Wearable")
    print("6. Social/Desafios")
    print("7. Vídeos")
    print("8. Recomendações")
    print("9. Feedback")
    print("10. Fórum")
    print("11. Atualizar senha")
    print("0. Logout")
    print("="*30)
    return input("Escolha uma opção: ")

def exibir_menu_principal():
    print("\n" + "="*30)
    print("=== Fitness App ===")
    print("="*30)
    print("1. Login")
    print("2. Registrar Usuário")
    print("3. Recuperar Senha")
    print("0. Sair")
    print("="*30)
    return input("Escolha uma opção: ")

def exibir_menu_atividades():
    print("\n--- Gerenciar Atividades ---")
    print("1. Listar minhas atividades")
    print("2. Registrar nova atividade")
    print("3. Deletar uma atividade")
    print("4. Atualizar uma atividade")
    print("0. Voltar ao menu principal")
    return input("Escolha uma opção: ")

def exibir_menu_treinos():
    print("\n--- Gerenciar Planos de Treino ---")
    print("1. Listar planos")
    print("2. Criar plano")
    print("3. Deletar plano")
    print("4. Associar vídeo favorito a um plano")
    print("5. Adicionar exercício a um plano")
    print("6. Remover exercício de um plano")
    print("7. Atualizar plano")
    print("0. Voltar ao menu principal")
    return input("Escolha uma opção: ")

def exibir_menu_nutricao():
    print("\n--- Gerenciar Nutrição ---")
    print("1. Listar registros")
    print("2. Registrar refeição")
    print("3. Deletar registro")
    print("4. Atualizar registro")
    print("5. Analisar Consumo")
    print("0. Voltar")
    return input("Escolha uma opção: ")

def exibir_menu_metas():
    print("\n--- Gerenciar Metas ---")
    print("1. Listar metas")
    print("2. Criar meta")
    print("3. Deletar meta")
    print("4. Atualizar meta")
    print("5. Verificar Progresso")
    print("6. Concluir Meta")
    print("0. Voltar")
    return input("Escolha uma opção: ")

def exibir_menu_wearable():
    print("\n--- Gerenciar Wearable ---")
    print("1. Listar dados registrados")
    print("2. Registrar novo dado manualmente")
    print("3. Deletar dado")
    print("4. Simular dado de wearable")
    print("5. Exportar dados para CSV")
    print("6. Importar dados de CSV")
    print("0. Voltar")
    return input("Escolha uma opção: ")

def exibir_menu_social():
    print("\n--- Social/Desafios ---")
    print("1. Listar desafios")
    print("2. Criar desafio")
    print("3. Participar de desafio")
    print("4. Ver participantes de desafio")
    print("5. Sair do Desafio")
    print("6. Atualizar Desafio")
    print("7. Deletar desafio")
    print("0. Voltar")
    return input("Escolha uma opção: ")

def exibir_menu_videos():
    print("\n--- Vídeos ---")
    print("1. Pesquisar vídeos no YouTube")
    print("2. Listar vídeos favoritos")
    print("3. Salvar vídeo pesquisado como favorito")
    print("4. Deletar vídeo favorito")
    print("0. Voltar")
    return input("Escolha uma opção: ")

def exibir_menu_recomendacoes():
    print("\n--- Recomendações ---")
    print("1. Recomendações de treino")
    print("2. Recomendações de nutrição")
    print("3. Diretrizes gerais")
    print("4. Grupos musculares")
    print("5. Mobilidade")
    print("6. Divisões semanais")
    print("7. Progressão")
    print("8. Considerações finais")
    print("9. Atualizar minhas preferências")
    print("0. Voltar")
    return input("Escolha uma opção: ")

def exibir_menu_feedback():
    print("\n--- Feedback ---")
    print("1. Enviar feedback")
    print("2. Listar feedbacks")
    print("3. Deletar meu feedback")
    print("4. Atualizar meu feedback")
    print("0. Voltar")
    return input("Escolha uma opção: ")

def exibir_menu_forum():
    print("\n--- Fórum ---")
    print("1. Criar Post")
    print("2. Listar Posts")
    print("3. Comentar em um Post")
    print("4. Listar Comentários de um Post")
    print("5. Listar todos os Conteúdos do Fórum")
    print("6. Exibir meus Conteúdos no Fórum")
    print("7. Deletar meu Post")
    print("8. Deletar meu Comentário")
    print("9. Atualizar meu Post")
    print("10. Atualizar meu Comentário")
    print("0. Voltar")
    return input("Escolha uma opção: ")

